server:
  port: 8080

spring:
  application:
    name: springmvc_tres

  datasource:
    url: jdbc:h2:mem:accdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
